version: '3.8'

services:
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./services/user-service/src:/app/src
    networks:
      - microservice-network

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - USER_SERVICE_URL=http://user-service:3000
      - NOTIFICATION_SERVICE_URL=http://notification-service:3002
    volumes:
      - ./services/order-service/src:/app/src
    depends_on:
      - user-service
      - notification-service
    networks:
      - microservice-network

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    volumes:
      - ./services/notification-service/src:/app/src
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
