name: Deploy to Staging

on:
  push:
    branches: [ develop ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, order-service, notification-service]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push
        run: |
          cd services/${{ matrix.service }}
          docker build -t gcr.io/$PROJECT_ID/${{ matrix.service }}:staging-$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/${{ matrix.service }}:staging-$GITHUB_SHA

      - name: Deploy to Cloud Run (Staging)
        run: |
          gcloud run deploy ${{ matrix.service }}-staging \
            --image gcr.io/$PROJECT_ID/${{ matrix.service }}:staging-$GITHUB_SHA \
            --platform managed \
            --region $GCP_REGION \
            --allow-unauthenticated \
            --port 3000 \
            --tag staging \
            --set-env-vars NODE_ENV=staging